---
- name: install python packages
  sudo: yes
  with_items: liberator_python_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: install pip packages
  sudo: yes
  pip:
    requirements: /vagrant/requirements.txt
    executable: pip-3.2

- name: configure liberator
  template:
    src: settings_dist.py.j2
    dest: /vagrant/liberator/settings_dist.py
    owner: vagrant
    group: vagrant

- name: migrate DB
  command: python3 manage.py migrate
  args:
    chdir: /vagrant
