---
- name: install packages
  sudo: yes
  with_items: liberator_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: install pip packages
  sudo: yes
  pip:
    requirements: /vagrant/requirements.txt
    executable: pip-3.2

- name: install python2 psycopg
  sudo: yes
  pip:
    name: psycopg2

- name: create liberator DB
  sudo: yes
  sudo_user: postgres
  postgresql_db:
    name: liberator
    encoding: 'UTF-8'
    template: 'template0'

- name: create liberator DB user
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    name: liberator
    password: liberator
    db: liberator

- name: configure liberator
  template:
    src: init.py.j2
    dest: /vagrant/project/settings/__init__.py

- name: migrate DB
  command: python3 manage.py migrate
  args:
    chdir: /vagrant

- name: load initial data
  sudo: yes
  command: python3 manage.py loaddata init
  args:
    chdir: /vagrant

- name: put /vagrant/bin in path
  template:
    src: profile.j2
    dest: ~/.profile
