---
galaxy_info:
  author: Goran Mekić
  description: DokuWiki
  license: GPLv3
  min_ansible_version: 1.6
  platforms:
    - name: Debian
      versions:
        - wheezy
  categories:
    - web
dependencies:
  - {role: common}
